name: .NET Core

on:
  push:
    branches: [ Dev , master ]
  pull_request:
    branches: [ Dev , master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Deploy Docker Image to Heroku App
  # You may pin to the exact commit or the version.
  # uses: jctaveras/heroku-deploy@7b87e8dd4665d3b667e0cf1633241a66e3abd396
      uses: jctaveras/heroku-deploy@v2.0.0
      with: 
    # Email Linked to your Heroku Account
        email: tarunreddykreddy@gmail.com
    # Your Heroku API Key
        api_key: 9d56e7ca-b6b5-4b24-b094-1e2ed3dce9d3
    # Your Heroku App Name
        app_name: interscom
    # Dokerfile path
        dockerfile_path: .
